version: 0.0
os: linux

files:
  - source: /
    destination: /home/ubuntu/myapp

hooks:
  ApplicationStop:
    - location: scripts/stop.sh
      timeout: 120
      runas: ubuntu
  AfterInstall:
    - location: scripts/start.sh
      timeout: 120
      runas: ubuntu
