version: 0.0
os: linux

hooks:
  ApplicationStop:
    - location: scripts/stop.sh
      timeout: 180
      runas: ubuntu
  AfterInstall:
    - location: scripts/start.sh
      timeout: 180
      runas: ubuntu
